project_id = "mspujwrfhbobrxhofxzv"

[functions.fetch-ghl-contacts]
verify_jwt = false

[functions.update-ghl-opportunity]
verify_jwt = false

[functions.fetch-contact-conversations]
verify_jwt = false

[functions.update-ghl-appointment]
verify_jwt = false

[functions.fetch-contact-notes]
verify_jwt = false
