project_id = "mspujwrfhbobrxhofxzv"

[functions.fetch-ghl-contacts]
verify_jwt = false

[functions.update-ghl-opportunity]
verify_jwt = false

[functions.fetch-contact-conversations]
verify_jwt = false

[functions.update-ghl-appointment]
verify_jwt = false

[functions.fetch-contact-notes]
verify_jwt = false

[functions.create-contact-note]
verify_jwt = false

[functions.create-ghl-task]
verify_jwt = false

[functions.delete-ghl-task]
verify_jwt = false

[functions.update-ghl-task]
verify_jwt = false

[functions.sync-ghl-tasks]
verify_jwt = false

[functions.fetch-all-ghl-tasks]
verify_jwt = false

[functions.create-ghl-entry]
verify_jwt = false

[functions.create-ghl-appointment]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.delete-ghl-appointment]
verify_jwt = false

[functions.delete-ghl-opportunity]
verify_jwt = false

[functions.sync-lost-opportunity-stages]
verify_jwt = false

[functions.import-ghl-location2]
verify_jwt = false

[functions.fix-location2-scope]
verify_jwt = false

[functions.update-contact-scope]
verify_jwt = false

[functions.update-contact-address]
verify_jwt = false

[functions.update-contact-source]
verify_jwt = false

[functions.update-contact-phone]
verify_jwt = false

[functions.bulk-update-source]
verify_jwt = false

[functions.update-contact-name]
verify_jwt = false

[functions.auto-create-never-answers-tasks]
verify_jwt = false

[functions.auto-abandon-pns-opportunities]
verify_jwt = false

[functions.ai-check-never-answers]
verify_jwt = false

[functions.update-opportunity-scope]
verify_jwt = false

[functions.update-opportunity-address]
verify_jwt = false

[functions.generate-estimate-scope]
verify_jwt = false
